spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "kalah"
      uuid-representation: standard

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"
